"""rename project_files indices from ix_files_ to ix_project_files_

Revision ID: 1c5ff84851a0
Revises: 66950337f9dc
Create Date: 2026-04-11 16:43:41.346420

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c5ff84851a0"
down_revision: str | Sequence[str] | None = "66950337f9dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_project_id"), table_name="project_files")
    op.drop_index(op.f("ix_files_project_type_active"), table_name="project_files", postgresql_where="(NOT is_active)")
    op.create_index(op.f("ix_project_files_project_id"), "project_files", ["project_id"], unique=False)
    op.create_index(
        "ix_project_files_project_type_active",
        "project_files",
        ["project_id", "file_type"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_project_files_project_type_active", table_name="project_files", postgresql_where=sa.text("is_active")
    )
    op.drop_index(op.f("ix_project_files_project_id"), table_name="project_files")
    op.create_index(
        op.f("ix_files_project_type_active"),
        "project_files",
        ["project_id", "file_type"],
        unique=False,
        postgresql_where="(NOT is_active)",
    )
    op.create_index(op.f("ix_files_project_id"), "project_files", ["project_id"], unique=False)
    # ### end Alembic commands ###
