"""add updated_by to projects

Revision ID: 5f4d22303d15
Revises: 7ff699e19f20
Create Date: 2026-04-05 01:14:55.251369

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f4d22303d15"
down_revision: str | Sequence[str] | None = "7ff699e19f20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.create_foreign_key("projects_updated_by_fkey", "projects", "users", ["updated_by"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("projects_updated_by_fkey", "projects", type_="foreignkey")
    op.drop_column("projects", "updated_by")
    # ### end Alembic commands ###
