"""add verification_token to users

Revision ID: f59248742306
Revises: 01325dbd8a16
Create Date: 2026-04-08 23:57:53.214634

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f59248742306"
down_revision: str | Sequence[str] | None = "01325dbd8a16"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("verification_token", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verification_token")
    # ### end Alembic commands ###
